const STAGES = [
  {
    id: 1,
    name: 'SCHOOLYARD',
    theme: 'school',
    goal: 'GATE',
    time: 99,
    viewRange: 108,
    seekerSpeed: 1.02,
    seekerChase: 2.28,
    clearTitle: 'GATE CLEAR',
    clearMsg: 'The yard is behind you. The street is next.',
    brief: [
      'Stage 1. Schoolyard after the bell.',
      'One seeker. Bushes hide you if you stay still.',
      'Toss a pebble. They chase the sound. Then reach the GATE.',
    ],
    map: [
      '################',
      '#......HH......#',
      '#..............#',
      '###..........###',
      '#..............#',
      '#.BB........BB.#',
      '#..............#',
      '#......C.......#',
      '#..............#',
      '#.BB........BB.#',
      '#..............#',
      '#......SS......#',
      '#.B...####...B.#',
      '################',
    ],
    patrols: [
      [{ c: 2, r: 6, wait: 0.8 }, { c: 13, r: 6, wait: 0.8 }],
    ],
  },
  {
    id: 2,
    name: 'SHOPPING ST.',
    theme: 'town',
    goal: 'ALLEY',
    time: 150,
    viewRange: 128,
    seekerSpeed: 1.12,
    seekerChase: 2.62,
    clearTitle: 'STREET CLEAR',
    clearMsg: 'Shops fade. The back alley is quieter. Maybe.',
    brief: [
      'Stage 2. The shopping street is lit.',
      'Three seekers. Toss a pebble. They think someone is there.',
      'Do not sprint the open road. Slip into the ALLEY.',
    ],
    map: [
      '################',
      '#HHBB.C.##.CVBB#',
      '#BB............#',
      '###.###..###.###',
      '#V.#C.#..#C.#VC#',
      '###.##....##.###',
      '#..............#',
      '#.BB.C.##.C.BB.#',
      '##.CV......VC.##',
      '#..............#',
      '####.##..##.####',
      '#.CV.BB..BB.VC.#',
      '#.C..BBBBBB.C..#',
      '#.C.BB....BB.C.#',
      '###.###..###.###',
      '#..............#',
      '#.BB.C.##.C.BB.#',
      '#C.....C.....C.#',
      '##............##',
      '#......SS......#',
      '#.B..######..B.#',
      '################',
    ],
    patrols: [
      [{ c: 2, r: 6, wait: 0.5 }, { c: 13, r: 6, wait: 0.5 }, { c: 13, r: 9, wait: 0.4 }, { c: 2, r: 9, wait: 0.4 }],
      [{ c: 4, r: 2, wait: 1.2 }, { c: 11, r: 2, wait: 1.2 }],
      [{ c: 3, r: 15, wait: 0.6 }, { c: 12, r: 15, wait: 0.6 }],
    ],
  },
  {
    id: 3,
    name: 'BACK ALLEY',
    theme: 'alley',
    goal: 'PARK',
    time: 160,
    viewRange: 118,
    seekerSpeed: 1.18,
    seekerChase: 2.7,
    clearTitle: 'ALLEY CLEAR',
    clearMsg: 'The walls end. Open grass. Nowhere to hide in a straight line.',
    brief: [
      'Stage 3. Narrow alleys. Corners are cover.',
      'Pebbles bounce off walls. Peek, then move.',
      'Cut through to the PARK gate.',
    ],
    map: [
      '################',
      '#HH............#',
      '##.##......##.##',
      '#..............#',
      '##.##......##.##',
      '#..##......##..#',
      '##.##......##.##',
      '#..............#',
      '##.##..BB..##.##',
      '#..............#',
      '##.##......##.##',
      '#..C........C..#',
      '##.##......##.##',
      '#..............#',
      '#.BB........BB.#',
      '#......SS......#',
      '#.B...####...B.#',
      '################',
    ],
    patrols: [
      [{ c: 2, r: 3, wait: 0.4 }, { c: 13, r: 3, wait: 0.4 }, { c: 13, r: 7, wait: 0.35 }, { c: 2, r: 7, wait: 0.35 }],
      [{ c: 2, r: 7, wait: 0.45 }, { c: 13, r: 7, wait: 0.45 }, { c: 13, r: 13, wait: 0.4 }, { c: 2, r: 13, wait: 0.4 }],
      [{ c: 5, r: 9, wait: 0.7 }, { c: 10, r: 9, wait: 0.7 }],
    ],
  },
  {
    id: 4,
    name: 'NIGHT PARK',
    theme: 'park',
    goal: 'STREET',
    time: 140,
    viewRange: 152,
    seekerSpeed: 1.16,
    seekerChase: 2.66,
    clearTitle: 'PARK CLEAR',
    clearMsg: 'Your street is close. Someone is waiting at the porch.',
    brief: [
      'Stage 4. The park is wide. Flashlights reach far.',
      'Trees only work if you stop. Crossing the lawn is loud.',
      'Reach the STREET home-side.',
    ],
    map: [
      '################',
      '#......HH......#',
      '#......BB......#',
      '#.BB.BB..BB.BB.#',
      '#..............#',
      '#....C....C....#',
      '#.BB........BB.#',
      '#..............#',
      '#..BB......BB..#',
      '#..............#',
      '#.C....##....C.#',
      '#..............#',
      '#.BB.BB..BB.BB.#',
      '#..............#',
      '#......SS......#',
      '#.B..........B.#',
      '################',
    ],
    patrols: [
      [{ c: 2, r: 4, wait: 0.55 }, { c: 13, r: 4, wait: 0.55 }],
      [{ c: 2, r: 7, wait: 0.4 }, { c: 13, r: 7, wait: 0.4 }, { c: 13, r: 11, wait: 0.4 }, { c: 2, r: 11, wait: 0.4 }],
      [{ c: 3, r: 9, wait: 0.6 }, { c: 12, r: 9, wait: 0.6 }],
    ],
  },
  {
    id: 5,
    name: 'HOME STREET',
    theme: 'home',
    goal: 'HOME',
    time: 180,
    viewRange: 140,
    seekerSpeed: 1.2,
    seekerChase: 2.78,
    clearTitle: "I'M HOME.",
    clearMsg: 'You slipped past every flashlight.',
    brief: [
      'Stage 5. Home street. The last seeker waits.',
      'He pauses and scans the porch. Do not walk the middle.',
      'Pebble, bush, then HOME. The light is on.',
    ],
    map: [
      '################',
      '#HHBB.C.##.CVBB#',
      '#BB............#',
      '###.###..###.###',
      '#V.#C.#..#C.#VC#',
      '###.##....##.###',
      '#..............#',
      '#.BB.C.##.C.BB.#',
      '##.CV......VC.##',
      '#..............#',
      '####.##..##.####',
      '#.CV.BB..BB.VC.#',
      '#.C..BBBBBB.C..#',
      '#.C.BB....BB.C.#',
      '###.###..###.###',
      '#..............#',
      '#.BB.C.##.C.BB.#',
      '#C.....C.....C.#',
      '##............##',
      '#......SS......#',
      '#.B..######..B.#',
      '################',
    ],
    patrols: [
      [{ c: 2, r: 6, wait: 0.45 }, { c: 13, r: 6, wait: 0.45 }, { c: 13, r: 9, wait: 0.35 }, { c: 2, r: 9, wait: 0.35 }],
      [{ c: 4, r: 2, wait: 2.0 }, { c: 11, r: 2, wait: 2.0 }],
      [{ c: 3, r: 15, wait: 0.5 }, { c: 12, r: 15, wait: 0.5 }],
      [{ c: 2, r: 13, wait: 0.5 }, { c: 13, r: 13, wait: 0.5 }],
    ],
  },
];
